name: marquee
description: 'A Flutter widget that scrolls text infinitely. Provides many
  customizations including custom scroll directions, durations, curves as well
  as pauses after every round.'
version: 2.3.0
repository: https://github.com/MarcelGarus/marquee

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
